services:
  birbola-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: birbola-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"  # Next.js default port
    networks:
      - birbola-shared-network
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    labels:
      - "com.birbola.service=frontend"

networks:
  #birbola-network:        # Islom-
  #  driver: bridge
  birbola-shared-network:  # Islom+
    external: true